### PR TITLE
Remove sudo prefix for change_url_app_ynh

### PR DESCRIPTION
**Pull request by JimboJoe**
to test that change_url scripts are actually run as root.

### CODE REVIEW

**Comment by alexAubin** [comment]
Were you able to check if the functional tests in the core still works ? :D

**Comment by JimboJoe** [comment]
No I'm sorry, I don't have a working ynh-dev environment at the moment :-/
But I tested the app.py patch on my test instance successfully.

**Comment by alexAubin** [comment]
Alright, I'll have a look :wink:

**Comment by JimboJoe** [comment]
By the way, what do you mean by "functional tests in the core"? Are there automated ones?

EDIT : I figured some of it out until `sudo /vagrant/ynh-dev test yunohost`.
Yet it fails on "tests/test_changeurl.py" (without my changes). Is there a documentation on how to setup tests?

**Comment by JimboJoe** [comment]
I passed the functional tests (`ynh-dev test yunohost`) OK with these changes and the [corresponding PR](https://github.com/YunoHost/yunohost/pull/329) in core.
Note that I had to patch `test_changeurl.py` this way (before the PRs changes):
```
 src/yunohost/tests/test_changeurl.py | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/src/yunohost/tests/test_changeurl.py b/src/yunohost/tests/test_changeurl.py
index 506060c..272d5e5 100644
--- a/src/yunohost/tests/test_changeurl.py
+++ b/src/yunohost/tests/test_changeurl.py
@@ -19,10 +19,14 @@ maindomain = _get_maindomain()
 
 
 def setup_function(function):
+    global auth
+    auth = init_authenticator(AUTH_IDENTIFIER, AUTH_PARAMETERS)
     pass
 
 
 def teardown_function(function):
+    global auth
+    auth = init_authenticator(AUTH_IDENTIFIER, AUTH_PARAMETERS)
     app_remove(auth, "change_url_app")
 
 
@@ -38,7 +42,7 @@ def check_changeurl_app(path):
 
     assert appmap[maindomain][path + "/"]["id"] == "change_url_app"
 
-    r = requests.get("https://%s%s/" % (maindomain, path))
+    r = requests.get("https://%s%s/" % (maindomain, path), verify=False)
     assert r.status_code == 200

**Review by alexAubin — APPROVED** [review]
Tested and reviewed

**Comment by JimboJoe** [comment]
And what about changes on test_changeurl.py?
Did you need them?

**Pull request merged**
